"""Shared authentication and RBAC for Immich Manager services."""

from .rbac import (
    Role,
    ensure_users_table,
    get_or_create_user,
    require_role,
    get_all_users,
    update_user_role,
    extract_token,
    validate_immich_token,
)

from .ip_gate import (
    ensure_ip_gate_tables,
    get_trusted_ip,
    insert_pending_ip,
    trust_ip,
    revoke_ip,
    unblock_ip,
    delete_ip,
    update_last_seen,
    update_ip_label,
    update_ip_trust_duration,
    expire_stale_ips,
    list_ips_by_status,
    record_ip_connection,
    get_ip_connections_count_7d,
    get_connection_log,
    create_verification_token,
    validate_verification_token,
    mark_token_used,
    is_valid_email,
    check_ip_access,
)

__all__ = [
    "Role",
    "ensure_users_table",
    "get_or_create_user",
    "require_role",
    "get_all_users",
    "update_user_role",
    "extract_token",
    "validate_immich_token",
    "ensure_ip_gate_tables",
    "get_trusted_ip",
    "insert_pending_ip",
    "trust_ip",
    "revoke_ip",
    "unblock_ip",
    "delete_ip",
    "update_last_seen",
    "update_ip_label",
    "update_ip_trust_duration",
    "expire_stale_ips",
    "list_ips_by_status",
    "record_ip_connection",
    "get_ip_connections_count_7d",
    "get_connection_log",
    "create_verification_token",
    "validate_verification_token",
    "mark_token_used",
    "is_valid_email",
    "check_ip_access",
]
